[project]
name = "llm-ocr-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "typer>=0.15.2",
    "uvicorn>=0.33.0",
]

[tool.uv.workspace]
members = ["llm/got-ocr-2.0-cpu"]
