# This file was auto-generated by Fern from our API Definition.

from .bad_request_error_body import BadRequestErrorBody
from .image_request import ImageRequest
from .internal_server_error_body import InternalServerErrorBody
from .ocr_result import OcrResult
from .ocr_result_metadata import OcrResultMetadata
from .post_ocr_by_bxn_local_ocr_response import PostOcrByBxnLocalOcrResponse
from .post_ocr_by_bxn_local_ocr_response_data import PostOcrByBxnLocalOcrResponseData

__all__ = [
    "BadRequestErrorBody",
    "ImageRequest",
    "InternalServerErrorBody",
    "OcrResult",
    "OcrResultMetadata",
    "PostOcrByBxnLocalOcrResponse",
    "PostOcrByBxnLocalOcrResponseData",
]
