# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class PostOcrByBxnLocalOcrResponseData(UniversalBaseModel):
    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    识别出的文本内容
    """

    confidence: typing.Optional[float] = pydantic.Field(default=None)
    """
    识别结果的置信度 (0-1)
    """

    time_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    OCR处理耗时(秒)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="forbid"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
