# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .post_ocr_by_bxn_local_ocr_response_data import PostOcrByBxnLocalOcrResponseData
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class PostOcrByBxnLocalOcrResponse(UniversalBaseModel):
    code: typing.Optional[int] = pydantic.Field(default=None)
    """
    状态码，0表示成功
    """

    msg: typing.Optional[str] = pydantic.Field(default=None)
    """
    状态信息
    """

    data: typing.Optional[PostOcrByBxnLocalOcrResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="forbid"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.forbid
