# This file was auto-generated by Fern from our API Definition.

from ..core.abstract_fern_service import AbstractFernService
import typing
from ..security import ApiAuth
from ..types.post_ocr_by_bxn_local_ocr_response import PostOcrByBxnLocalOcrResponse
import abc
import fastapi
import inspect
from ..security import FernAuth
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..core.exceptions.fern_http_exception import FernHTTPException
import logging
import functools
from ..core.route_args import get_route_args


class AbstractRootService(AbstractFernService):
    """
    AbstractRootService is an abstract class containing the methods that you should implement.

    Each method is associated with an API route, which will be registered
    with FastAPI when you register your implementation using Fern's register()
    function.
    """

    @abc.abstractmethod
    def post_ocr_by_bxn_local_ocr(
        self, *, base_64_image: typing.Optional[str] = None, auth: ApiAuth
    ) -> PostOcrByBxnLocalOcrResponse:
        """
        上传图片并返回OCR识别结果
        """
        ...

    """
    Below are internal methods used by Fern to register your implementation.
    You can ignore them.
    """

    @classmethod
    def _init_fern(cls, router: fastapi.APIRouter) -> None:
        cls.__init_post_ocr_by_bxn_local_ocr(router=router)

    @classmethod
    def __init_post_ocr_by_bxn_local_ocr(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.post_ocr_by_bxn_local_ocr)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(
            endpoint_function.parameters.items()
        ):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "base_64_image":
                new_parameters.append(
                    parameter.replace(default=fastapi.Body(alias="base64_image"))
                )
            elif parameter_name == "auth":
                new_parameters.append(
                    parameter.replace(default=fastapi.Depends(FernAuth))
                )
            else:
                new_parameters.append(parameter)
        setattr(
            cls.post_ocr_by_bxn_local_ocr,
            "__signature__",
            endpoint_function.replace(parameters=new_parameters),
        )

        @functools.wraps(cls.post_ocr_by_bxn_local_ocr)
        def wrapper(
            *args: typing.Any, **kwargs: typing.Any
        ) -> PostOcrByBxnLocalOcrResponse:
            try:
                return cls.post_ocr_by_bxn_local_ocr(*args, **kwargs)
            except (BadRequestError, InternalServerError) as e:
                raise e
            except FernHTTPException as e:
                logging.getLogger(f"{cls.__module__}.{cls.__name__}").warn(
                    f"Endpoint 'post_ocr_by_bxn_local_ocr' unexpectedly threw {e.__class__.__name__}. "
                    + f"If this was intentional, please add {e.__class__.__name__} to "
                    + "the endpoint's errors list in your Fern Definition."
                )
                raise e

        # this is necessary for FastAPI to find forward-ref'ed type hints.
        # https://github.com/tiangolo/fastapi/pull/5077
        wrapper.__globals__.update(cls.post_ocr_by_bxn_local_ocr.__globals__)

        router.post(
            path="/v1/ocr_by_bxn_local_ocr",
            response_model=PostOcrByBxnLocalOcrResponse,
            description=AbstractRootService.post_ocr_by_bxn_local_ocr.__doc__,
            **get_route_args(cls.post_ocr_by_bxn_local_ocr, default_tag=""),
        )(wrapper)
